# Generated by Django 6.1.1 on 2026-09-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
